-- Ecommerce Pulse - persons and relations for the harvested owners.
-- Data from docs/ENTITY-DATA.md.

INSERT OR IGNORE INTO persons (id, name, linkedin_url)
VALUES
  ('mikolaj-konopskyy', 'Mikołaj Konopskyy', NULL),
  ('daniel-walendziak', 'Daniel Walendziak', NULL),
  ('krzysztof-sawicki', 'Krzysztof Sawicki', NULL),
  ('weronika-bros', 'Weronika Broś', 'https://www.linkedin.com/in/weronika-bro%C5%9B-54bb39250/'),
  ('wojciech-gola', 'Wojciech Maciej Gola', NULL),
  ('sofia-sivokha', 'Sofiia Sivokha', NULL),
  ('isamupt', 'isamupt', NULL),
  ('d3tailer', 'd3tailer', NULL),
  ('pompa-team', 'Pompa Team', NULL),
  ('karolina-preiss', 'Karolina Preiss', NULL),
  ('agnieszka-kalita', 'Agnieszka Kalita', NULL),
  ('tomekklata', 'Tomasz (tomekklata)', NULL),
  ('skolim', 'Skolim', NULL),
  ('samuel-onuha', 'Samuel Onuha', NULL),
  ('ruben-onuha', 'Ruben Onuha', NULL),
  ('kubanczyk', 'Kubanczyk', NULL),
  ('oskar-lipinski', 'Oskar Lipiński', NULL),
  ('orzechowski-robert', 'Orzechowski Robert', NULL),
  ('sikora-pawel', 'Sikora Paweł', NULL),
  ('owczarzak-michal', 'Owczarzak Michał', NULL),
  ('sakowski-michal', 'Sakowski Michał', NULL),
  ('discokarol', 'discokarol_', NULL),
  ('dajczmanhubert', 'Hubert Dajczman', NULL),
  ('pirlo444', 'pirlo444_', NULL),
  ('bedoes2115', 'bedoes2115', NULL),
  ('sabina-hajdo-piorek', 'Sabina Hajdo-Piórek', NULL),
  ('pawel-piorek', 'Paweł Piórek', NULL),
  ('sebastian-czajewski', 'Sebastian Czajewski', NULL),
  ('ksiazulo', 'ksiazulo', NULL),
  ('jaroslaw-jarzabkowski', 'Jarosław Jarząbkowski (Pasha Biceps)', NULL),
  ('michal-matczak', 'Michał Matczak', NULL),
  ('agata-fak', 'Agata Fąk', NULL),
  ('wojan-official', 'wojan_official', NULL),
  ('ula-kowalska', 'Ula Kowalska', NULL),
  ('zuza-fijak', 'Zuza Fijak', NULL),
  ('agnieszka-nowakowska', 'Agnieszka Nowakowska', NULL),
  ('julia-turewicz', 'Julia Turewicz', NULL),
  ('justyna-przygonska', 'Justyna Przygońska', NULL),
  ('brygida-handzelewicz-waclawek', 'Brygida Handzelewicz-Wacławek', NULL),
  ('marek-zimniak', 'Marek Zimniak', NULL),
  ('kamil-galant', 'Kamil Galant', NULL),
  ('marcin-galant', 'Marcin Galant', NULL),
  ('zuzanna-grabowska', 'Zuzanna Irena Grabowska', NULL);

INSERT OR IGNORE INTO socials (owner_kind, owner_id, platform, handle, url)
VALUES
  ('person', 'mikolaj-konopskyy', 'instagram', 'konopskyy_', 'https://www.instagram.com/konopskyy_/'),
  ('person', 'mikolaj-konopskyy', 'youtube', 'Konopskyy', 'https://www.youtube.com/@Konopskyy'),
  ('person', 'weronika-bros', 'instagram', 'weronikabros', 'https://www.instagram.com/weronikabros/'),
  ('person', 'sofia-sivokha', 'instagram', 'sofisivokha', 'https://www.instagram.com/sofisivokha/'),
  ('person', 'isamupt', 'instagram', 'isamupt', 'https://www.instagram.com/isamupt/'),
  ('person', 'isamupt', 'facebook', 'IsAmUxPompa69', 'https://www.facebook.com/IsAmUxPompa69/'),
  ('person', 'd3tailer', 'instagram', 'd3tailer', 'https://www.instagram.com/d3tailer/'),
  ('person', 'd3tailer', 'facebook', 'detailer.official', 'https://www.facebook.com/detailer.official/'),
  ('person', 'pompa-team', 'instagram', 'pompa.team', 'https://www.instagram.com/pompa.team/'),
  ('person', 'pompa-team', 'facebook', 'pompateamofficial', 'https://www.facebook.com/pompateamofficial/'),
  ('person', 'karolina-preiss', 'instagram', 'karolina_preiss', 'https://www.instagram.com/karolina_preiss/'),
  ('person', 'agnieszka-kalita', 'instagram', 'agakalitaa', 'https://www.instagram.com/agakalitaa/'),
  ('person', 'tomekklata', 'instagram', 'tomekklata', 'https://www.instagram.com/tomekklata/'),
  ('person', 'skolim', 'instagram', 'skolim__', 'https://www.instagram.com/skolim__/'),
  ('person', 'skolim', 'facebook', 'SKOLIMoficjalnie', 'https://www.facebook.com/SKOLIMoficjalnie/'),
  ('person', 'samuel-onuha', 'instagram', 'realonuha', 'https://www.instagram.com/realonuha/'),
  ('person', 'samuel-onuha', 'youtube', 'SamuelOnuha', 'https://www.youtube.com/@SamuelOnuha'),
  ('person', 'ruben-onuha', 'instagram', 'ruub', 'https://www.instagram.com/ruub/'),
  ('person', 'ruben-onuha', 'youtube', 'rubenuonuha', 'https://www.youtube.com/@rubenuonuha'),
  ('person', 'kubanczyk', 'instagram', 'kubanczyk.official', 'https://www.instagram.com/kubanczyk.official/'),
  ('person', 'kubanczyk', 'facebook', 'KubanczykProdukcja', 'https://www.facebook.com/KubanczykProdukcja/'),
  ('person', 'oskar-lipinski', 'instagram', 'oscarlipinsky', 'https://www.instagram.com/oscarlipinsky/'),
  ('person', 'oskar-lipinski', 'youtube', 'oskarlipinski', 'https://www.youtube.com/@oskarlipinski'),
  ('person', 'orzechowski-robert', 'instagram', 'robercik_dynamit', 'https://www.instagram.com/robercik_dynamit/'),
  ('person', 'sikora-pawel', 'instagram', 'ponczek_endomorfik', 'https://www.instagram.com/ponczek_endomorfik/'),
  ('person', 'owczarzak-michal', 'instagram', 'owcawk', 'https://www.instagram.com/owcawk/'),
  ('person', 'sakowski-michal', 'instagram', 'sakerwk', 'https://www.instagram.com/sakerwk/'),
  ('person', 'discokarol', 'instagram', 'discokarol_', 'https://www.instagram.com/discokarol_/'),
  ('person', 'dajczmanhubert', 'instagram', 'dajczmanhubert', 'https://www.instagram.com/dajczmanhubert/'),
  ('person', 'pirlo444', 'instagram', 'pirlo444_', 'https://www.instagram.com/pirlo444_/'),
  ('person', 'bedoes2115', 'instagram', 'bedoes2115', 'https://www.instagram.com/bedoes2115/'),
  ('person', 'sebastian-czajewski', 'instagram', 'czvjnik', 'https://www.instagram.com/czvjnik/'),
  ('person', 'sebastian-czajewski', 'facebook', '102286502728984', 'https://www.facebook.com/102286502728984/'),
  ('person', 'sebastian-czajewski', 'youtube', 'czvjnik', 'https://www.youtube.com/@czvjnik'),
  ('person', 'ksiazulo', 'instagram', 'ksiazulo', 'https://www.instagram.com/ksiazulo/'),
  ('person', 'ksiazulo', 'youtube', 'ksiazulo', 'https://www.youtube.com/@ksiazulo'),
  ('person', 'jaroslaw-jarzabkowski', 'instagram', 'pashabiceps', 'https://www.instagram.com/pashabiceps/'),
  ('person', 'jaroslaw-jarzabkowski', 'facebook', 'G5.pasha', 'https://www.facebook.com/G5.pasha/'),
  ('person', 'michal-matczak', 'instagram', '33mata', 'https://www.instagram.com/33mata/'),
  ('person', 'agata-fak', 'instagram', 'fagataaa', 'https://www.instagram.com/fagataaa/'),
  ('person', 'agata-fak', 'facebook', '100081290535607', 'https://www.facebook.com/p/Agata-F%C4%85k-100081290535607/'),
  ('person', 'wojan-official', 'instagram', 'wojan_official', 'https://www.instagram.com/wojan_official/'),
  ('person', 'ula-kowalska', 'instagram', 'ulakowalska_official', 'https://www.instagram.com/ulakowalska_official/'),
  ('person', 'zuza-fijak', 'instagram', 'suziontop', 'https://www.instagram.com/suziontop/'),
  ('person', 'agnieszka-nowakowska', 'instagram', 'agaanowakowska', 'https://www.instagram.com/agaanowakowska/'),
  ('person', 'julia-turewicz', 'instagram', 'juliajanulewicz', 'https://www.instagram.com/juliajanulewicz/'),
  ('person', 'justyna-przygonska', 'instagram', 'justyna_przygonska', 'https://www.instagram.com/justyna_przygonska/'),
  ('person', 'brygida-handzelewicz-waclawek', 'instagram', 'brygidamagdalena', 'https://www.instagram.com/brygidamagdalena/'),
  ('person', 'marek-zimniak', 'instagram', 'royalwatch.pl', 'https://www.instagram.com/royalwatch.pl/'),
  ('person', 'kamil-galant', 'instagram', 'kmileko', 'https://www.instagram.com/kmileko/'),
  ('person', 'marcin-galant', 'instagram', 'martinfriendlyscott', 'https://www.instagram.com/martinfriendlyscott/'),
  ('person', 'marcin-galant', 'tiktok', 'martinfknscott', 'https://www.tiktok.com/@martinfknscott'),
  ('person', 'zuzanna-grabowska', 'instagram', 'sanahmusic', 'https://www.instagram.com/sanahmusic/');

INSERT OR IGNORE INTO person_relations (person_id, entity_id, role, label, from_day, to_day)
VALUES
  ('mikolaj-konopskyy', 'mushi', 'owner', 'prezes', NULL, NULL),
  ('daniel-walendziak', 'gymglamour', 'owner', 'prezes', NULL, NULL),
  ('krzysztof-sawicki', 'laboratoriumpanidomu', 'owner', 'prezes', NULL, NULL),
  ('weronika-bros', 'emereedivine', 'owner', 'wspólnik', NULL, NULL),
  ('wojciech-gola', 'emereedivine', 'owner', 'wspólnik', NULL, NULL),
  ('sofia-sivokha', 'emereedivine', 'owner', 'wspólnik', NULL, NULL),
  ('sofia-sivokha', 'gymglamour', 'influencer', 'influ', NULL, NULL),
  ('isamupt', 'risky', 'owner', 'właściciel', NULL, NULL),
  ('d3tailer', 'risky', 'owner', 'właściciel', NULL, NULL),
  ('pompa-team', 'risky', 'owner', 'właściciel', NULL, NULL),
  ('karolina-preiss', 'godsavequeens', 'owner', 'właściciel', NULL, NULL),
  ('agnieszka-kalita', 'booso', 'owner', 'JDG', NULL, NULL),
  ('tomekklata', 'booso', 'owner', 'właściciel', NULL, NULL),
  ('skolim', 'sklepskolim', 'owner', 'właściciel', NULL, NULL),
  ('samuel-onuha', 'icon-amsterdam', 'owner', 'właściciel', NULL, NULL),
  ('ruben-onuha', 'icon-amsterdam', 'owner', 'właściciel', NULL, NULL),
  ('kubanczyk', 'wakenbake', 'owner', 'właściciel', NULL, NULL),
  ('oskar-lipinski', 'e-daag', 'owner', 'właściciel', NULL, NULL),
  ('orzechowski-robert', 'wkdzik', 'owner', 'wspólnik 25%', NULL, NULL),
  ('sikora-pawel', 'wkdzik', 'owner', 'wspólnik 25%', NULL, NULL),
  ('owczarzak-michal', 'wkdzik', 'owner', 'wspólnik 25%', NULL, NULL),
  ('sakowski-michal', 'wkdzik', 'owner', 'wspólnik 25%', NULL, NULL),
  ('discokarol', 'brokies', 'owner', 'właściciel', NULL, NULL),
  ('dajczmanhubert', 'brokies', 'owner', 'właściciel', NULL, NULL),
  ('pirlo444', 'brokies', 'owner', 'właściciel', NULL, NULL),
  ('bedoes2115', 'brokies', 'influencer', 'influ', NULL, NULL),
  ('sabina-hajdo-piorek', 'rever', 'owner', 'właściciel', NULL, NULL),
  ('pawel-piorek', 'rever', 'owner', 'JDG', NULL, NULL),
  ('sebastian-czajewski', 'friendzstore', 'owner', 'właściciel', NULL, NULL),
  ('ksiazulo', 'mualasklep', 'owner', 'właściciel', NULL, NULL),
  ('jaroslaw-jarzabkowski', 'papitoenergy', 'owner', 'właściciel', NULL, NULL),
  ('michal-matczak', '33mata', 'owner', 'właściciel', NULL, NULL),
  ('agata-fak', 'fagata', 'owner', 'JDG', NULL, NULL),
  ('wojan-official', 'wojanshop', 'owner', 'właściciel', NULL, NULL),
  ('ula-kowalska', 'islandrecords', 'owner', 'wspólnik', NULL, NULL),
  ('zuza-fijak', 'islandrecords', 'owner', 'wspólnik', NULL, NULL),
  ('agnieszka-nowakowska', 'islandrecords', 'owner', 'wspólnik', NULL, NULL),
  ('julia-turewicz', 'nago', 'owner', 'właściciel', NULL, NULL),
  ('justyna-przygonska', 'theodderside', 'owner', 'współzałożycielka', NULL, NULL),
  ('brygida-handzelewicz-waclawek', 'theodderside', 'owner', 'współzałożycielka', NULL, NULL),
  ('marek-zimniak', 'royalwatch', 'owner', 'właściciel', NULL, NULL),
  ('kamil-galant', 'premieresociety', 'owner', 'współtwórca', NULL, NULL),
  ('marcin-galant', 'premieresociety', 'owner', 'współtwórca', NULL, NULL),
  ('zuzanna-grabowska', 'sanah', 'owner', 'artystka 1:1', NULL, NULL);
