import type { ProviderConfig } from './types.ts';

export const LEGACY_PROVIDERS: readonly ProviderConfig[] = [
  {
    id: 'misbhv',
    domain: 'misbhv.com',
    platform: 'shopify',
    schedule: '15 5 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'embedded-json',
    ratePerSecond: 2,
    durationSeconds: 1800,
    requiresProxy: false,
    endpoint: 'https://misbhv.com/products.json',
    enabled: false,
  },
  {
    id: 'montiel',
    domain: 'montiel.com',
    platform: 'shopify',
    schedule: '0 7 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'embedded-json',
    ratePerSecond: 2,
    durationSeconds: 1000,
    requiresProxy: false,
    endpoint: 'https://montiel.com/products.json',
    enabled: false,
  },
  {
    id: 'noo-ma',
    domain: 'noo.ma',
    platform: 'shopify',
    schedule: '0 8 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'embedded-json',
    ratePerSecond: 2,
    durationSeconds: 1500,
    requiresProxy: false,
    endpoint: 'https://noo.ma/products.json',
    enabled: false,
  },
  {
    id: 'magdabutrym',
    domain: 'magdabutrym.com',
    platform: 'shopify',
    schedule: '0 11 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'embedded-json',
    ratePerSecond: 2,
    durationSeconds: 600,
    requiresProxy: false,
    endpoint: 'https://www.magdabutrym.com/sitemap-category/all.xml',
    enabled: false,
  },
  {
    id: 'shapellx',
    domain: 'www.shapellx.com',
    platform: 'shopify',
    schedule: '0 13 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'embedded-json',
    ratePerSecond: 1,
    durationSeconds: 120,
    requiresProxy: false,
    endpoint: 'https://www.shapellx.com/',
    enabled: false,
  },
  {
    id: 'seembols',
    domain: 'seembols.com',
    platform: 'shopify',
    schedule: '0 14 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'embedded-json',
    ratePerSecond: 1,
    durationSeconds: 300,
    requiresProxy: false,
    endpoint: 'https://seembols.com/',
    enabled: false,
  },
  {
    id: 'westwing',
    domain: 'www.westwing.pl',
    platform: 'shopify',
    schedule: '0 15 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'embedded-json',
    ratePerSecond: 1,
    durationSeconds: 300,
    requiresProxy: false,
    endpoint: 'https://www.westwing.pl/',
    enabled: false,
  },
  {
    id: 'deehome',
    domain: 'deehome.pl',
    platform: 'woocommerce',
    schedule: '0 17 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'cart-probe',
    ratePerSecond: 1,
    durationSeconds: 300,
    requiresProxy: true,
    endpoint: 'https://deehome.pl/sklep/',
    enabled: false,
  },
  {
    id: 'bloozie',
    domain: 'www.bloozie.pl',
    platform: 'shopify',
    schedule: '0 14 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'embedded-json',
    ratePerSecond: 1,
    durationSeconds: 180,
    requiresProxy: false,
    endpoint: 'https://www.bloozie.pl/products.json',
    enabled: false,
  },
  {
    id: 'foodsbyann',
    domain: 'foodsbyann.com',
    platform: 'custom',
    schedule: '0 9 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'html',
    ratePerSecond: 1,
    durationSeconds: 300,
    requiresProxy: false,
    endpoint: 'https://foodsbyann.com/sitemap.xml.gz',
    enabled: false,
  },
  {
    id: 'laboratoriumpanidomu',
    domain: 'laboratoriumpanidomu.pl',
    platform: 'prestashop',
    schedule: '0 10 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'cart-probe',
    ratePerSecond: 1,
    durationSeconds: 250,
    requiresProxy: true,
    endpoint: 'https://laboratoriumpanidomu.pl/',
    enabled: false,
  },
  {
    id: 'phlov',
    domain: 'www.phlov.com',
    platform: 'prestashop',
    schedule: '0 12 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'cart-probe',
    ratePerSecond: 1,
    durationSeconds: 300,
    requiresProxy: false,
    endpoint: 'https://www.phlov.com/',
    enabled: false,
  },
  {
    id: 'influcenter',
    domain: 'influcenter.pl',
    platform: 'magento',
    schedule: '0 18 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'embedded-json',
    ratePerSecond: 2,
    durationSeconds: 600,
    requiresProxy: false,
    endpoint: 'https://influcenter.pl/',
    enabled: false,
  },
  {
    id: 'lexon',
    domain: 'lexon-design.com',
    platform: 'magento',
    schedule: '30 18 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'embedded-json',
    ratePerSecond: 2,
    durationSeconds: 300,
    requiresProxy: false,
    endpoint: 'https://lexon-design.com/en',
    enabled: false,
  },
  {
    id: 'arustamian',
    domain: 'arustamian.com',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 1,
    durationSeconds: 1000,
    requiresProxy: true,
    endpoint: 'https://arustamian.com/webapi/front/pl_PL/products/PLN/list',
    enabled: false,
  },
  {
    id: 'e-daag',
    domain: 'e-daag.com.pl',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 1,
    durationSeconds: 1300,
    requiresProxy: true,
    endpoint: 'https://e-daag.com.pl/webapi/front/pl_PL/products/PLN/list',
    enabled: false,
  },
  {
    id: 'emereedivine',
    domain: 'emereedivine.com',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 1,
    durationSeconds: 40,
    requiresProxy: true,
    endpoint: 'https://emereedivine.com/webapi/front/pl_PL/products/PLN/list',
    enabled: false,
  },
  {
    id: 'sklepskolim',
    domain: 'sklepskolim.pl',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 1,
    durationSeconds: 700,
    requiresProxy: true,
    endpoint: 'https://sklepskolim.pl/webapi/front/pl_PL/products/PLN/list',
    enabled: false,
  },
  {
    id: 'wkdzik',
    domain: 'wkdzik.pl',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 1,
    durationSeconds: 1000,
    requiresProxy: true,
    endpoint: 'https://wkdzik.pl/webapi/front/pl_PL/products/PLN/list',
    enabled: false,
  },
  {
    id: 'osmpower',
    domain: 'osmpower.pl',
    platform: 'shoper',
    schedule: '35 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 1,
    durationSeconds: 600,
    requiresProxy: true,
    endpoint: 'https://osmpower.pl/webapi/front/pl_PL/products/PLN/list',
    enabled: false,
  },
];
