import type { AdaptiveRateConfig, ProviderConfig } from './types.ts';
import { assertNonEmptyString, assertPositiveFinite, assertPositiveInteger } from './helpers.ts';
import { EXCLUDED_STOCK_IDS } from './providers/shoper/excluded-stock-ids.ts';
import { LEGACY_PROVIDERS } from './config.legacy.ts';

function validateAdaptiveRate(rate: AdaptiveRateConfig): AdaptiveRateConfig {
  assertPositiveFinite(rate.minRequestsPerSecond, 'config.adaptiveRate.minRequestsPerSecond');
  assertPositiveFinite(rate.maxRequestsPerSecond, 'config.adaptiveRate.maxRequestsPerSecond');
  assertPositiveFinite(rate.startRequestsPerSecond, 'config.adaptiveRate.startRequestsPerSecond');
  if (
    rate.minRequestsPerSecond > rate.startRequestsPerSecond ||
    rate.startRequestsPerSecond > rate.maxRequestsPerSecond
  ) {
    throw new Error('config.adaptiveRate must satisfy min <= start <= max');
  }
  if (!Number.isFinite(rate.backoffFactor) || rate.backoffFactor <= 0 || rate.backoffFactor >= 1) {
    throw new Error('config.adaptiveRate.backoffFactor must be in (0, 1)');
  }
  assertPositiveFinite(rate.recoveryStep, 'config.adaptiveRate.recoveryStep');
  if (!Number.isInteger(rate.recoveryCount) || rate.recoveryCount < 1) {
    throw new Error('config.adaptiveRate.recoveryCount must be a positive integer');
  }
  return rate;
}

export function validateConfig(config: ProviderConfig): ProviderConfig {
  assertNonEmptyString(config.id, 'config.id');
  assertNonEmptyString(config.domain, 'config.domain');
  assertNonEmptyString(config.schedule, 'config.schedule');
  assertNonEmptyString(config.endpoint, 'config.endpoint');
  assertPositiveInteger(config.ratePerSecond, 'config.ratePerSecond');
  if (config.adaptiveRate !== undefined) {
    validateAdaptiveRate(config.adaptiveRate);
  }
  return config;
}

const RAW_CONFIGS: readonly ProviderConfig[] = [
  // Web - exact stock via HTML/JSON (GET), no mutation, no proxy
  {
    id: 'rever',
    domain: 'rever.com.pl',
    platform: 'woocommerce',
    schedule: '45 4 * * *',
    window: 'both',
    mode: 'cf-get',
    stockSource: 'html',
    ratePerSecond: 1,
    durationSeconds: 40,
    requiresProxy: false,
    endpoint: 'https://rever.com.pl/product-sitemap.xml',
    enabled: true,
    currency: 'PLN',
    entityId: 'rever',
  },
  {
    id: 'dobrerzeczy',
    domain: 'dobrerzeczy.pl',
    platform: 'custom',
    schedule: '0 6 * * *',
    window: 'both',
    mode: 'vps-get',
    stockSource: 'html',
    ratePerSecond: 1,
    durationSeconds: 5,
    requiresProxy: true,
    endpoint: 'https://dobrerzeczy.pl/',
    enabled: true,
    currency: 'PLN',
    entityId: 'dobrerzeczy',
  },
  {
    id: 'royalwatch',
    domain: 'royalwatch.pl',
    platform: 'woocommerce',
    schedule: '45 4 * * *',
    window: 'both',
    mode: 'cf-get',
    stockSource: 'html',
    ratePerSecond: 1,
    durationSeconds: 65,
    requiresProxy: false,
    endpoint: 'https://www.royalwatch.pl/product-sitemap.xml',
    enabled: true,
    currency: 'PLN',
    entityId: 'royalwatch',
  },
  {
    id: 'mushi',
    domain: 'mushi.pl',
    platform: 'custom',
    schedule: '45 4 * * *',
    window: 'both',
    mode: 'cf-get',
    stockSource: 'html',
    ratePerSecond: 1,
    durationSeconds: 15,
    requiresProxy: false,
    endpoint: 'https://www.mushi.pl/sitemap.xml',
    enabled: true,
    currency: 'PLN',
    entityId: 'mushi',
  },
  {
    id: 'premieresociety',
    domain: 'premieresociety.com',
    platform: 'custom',
    schedule: '45 4 * * *',
    window: 'both',
    mode: 'cf-get',
    stockSource: 'html',
    ratePerSecond: 1,
    durationSeconds: 70,
    requiresProxy: false,
    endpoint: 'https://premieresociety.com/pl/3-sklep',
    enabled: false,
    currency: 'PLN',
    entityId: 'premieresociety',
  },
  // MCP Shopify
  {
    id: 'derichgallery',
    domain: 'derichgallery.com',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://derichgallery.com/products.json',
    enabled: true,
    currency: 'USD',
    entityId: 'derichgallery',
  },
  {
    id: 'monartofficial',
    domain: 'monartofficial.com',
    platform: 'shopify',
    schedule: '15 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 60,
    requiresProxy: true,
    endpoint: 'https://monartofficial.com/products.json',
    enabled: true,
    currency: 'EUR',
    entityId: 'monartofficial',
  },
  {
    id: 'booso',
    domain: 'booso.pl',
    platform: 'shopify',
    schedule: '15 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://booso.pl/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'booso',
  },
  {
    id: 'forcer',
    domain: 'forcer.pl',
    platform: 'shopify',
    schedule: '0 5 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 10,
    requiresProxy: true,
    endpoint: 'https://forcer.pl/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'forcer',
  },
  {
    id: 'godsavequeens',
    domain: 'pl.godsavequeens.com',
    platform: 'shopify',
    schedule: '15 3 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 20,
    requiresProxy: true,
    endpoint: 'https://pl.godsavequeens.com/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'godsavequeens',
  },
  {
    id: 'gymglamour',
    domain: 'gymglamour.com',
    platform: 'shopify',
    schedule: '0 1 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 40,
    requiresProxy: true,
    endpoint: 'https://gymglamour.com/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'gymglamour',
  },
  {
    id: 'hdrey',
    domain: 'hdrey.com',
    platform: 'shopify',
    schedule: '15 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 15,
    requiresProxy: true,
    endpoint: 'https://hdrey.com/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'hdrey-group',
  },
  {
    id: 'icon-amsterdam',
    domain: 'icon-amsterdam.com',
    platform: 'shopify',
    schedule: '0 16 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://icon-amsterdam.com/products.json',
    enabled: true,
    currency: 'EUR',
    entityId: 'icon-amsterdam',
  },
  {
    id: 'nago',
    domain: 'nago.com',
    platform: 'shopify',
    schedule: '0 12 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 15,
    requiresProxy: true,
    endpoint: 'https://nago.com/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'nago',
  },
  {
    id: 'theodderside',
    domain: 'theodderside.com',
    platform: 'shopify',
    schedule: '30 3 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://theodderside.com/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'theodderside',
  },
  {
    id: 'wakenbake',
    domain: 'wakenbake.pl',
    platform: 'shopify',
    schedule: '15 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 10,
    requiresProxy: true,
    endpoint: 'https://wakenbake.pl/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'wakenbake',
  },
  {
    id: 'wojanshop',
    domain: 'wojanshop.pl',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 60,
    requiresProxy: true,
    endpoint: 'https://wojanshop.pl/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'wojanshop',
  },
  {
    id: 'sanah',
    domain: 'sanah.shop',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 60,
    requiresProxy: true,
    endpoint: 'https://sanah.shop/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'sanah',
  },
  {
    id: '33mata',
    domain: '33mata.pl',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://33mata.pl/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: '33mata',
  },
  {
    id: 'mualasklep',
    domain: 'mualasklep.pl',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://mualasklep.pl/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'mualasklep',
  },
  {
    id: 'papitoenergy',
    domain: 'papitoenergy.com',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://www.papitoenergy.com/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'papitoenergy',
  },
  {
    id: 'friendzstore',
    domain: 'friendzstore.pl',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://friendzstore.pl/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'friendzstore',
  },
  {
    id: 'berecords',
    domain: 'berecords.pl',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://berecords.pl/products.json',
    enabled: false,
    currency: 'PLN',
    entityId: 'berecords',
  },
  {
    id: 'fagata',
    domain: 'fagata.com',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://fagata.com/products.json',
    enabled: false,
    currency: 'PLN',
    entityId: 'fagata',
  },
  {
    id: 'beaumont',
    domain: 'beaumont.eu',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://beaumont.eu/products.json',
    enabled: true,
    currency: 'EUR',
    entityId: 'beaumont',
  },
  {
    id: 'islandrecords',
    domain: 'islandrecords.pl',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 30,
    requiresProxy: true,
    endpoint: 'https://islandrecords.pl/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'islandrecords',
  },
  // UCP (Universal Commerce Protocol) stock. The old /api/mcp dies on
  // 31 Aug 2026. UCP is the replacement. See docs/UCP-MIGRATION.md.
  {
    id: 'icedstuff',
    domain: 'icedstuff.pl',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 120,
    requiresProxy: true,
    endpoint: 'https://icedstuff.pl/products.json',
    enabled: true,
    currency: 'PLN',
    entityId: 'icedstuff',
  },
  {
    id: 'divesmed',
    domain: 'divesmed.pl',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 60,
    requiresProxy: true,
    endpoint: 'https://divesmed.pl/products.json',
    enabled: true,
    currency: 'PLN',
  },
  {
    id: 'acewarsaw',
    domain: 'www.acewarsaw.pl',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 120,
    requiresProxy: true,
    endpoint: 'https://www.acewarsaw.pl/products.json',
    entityId: 'acewarsaw',
    enabled: true,
    currency: 'PLN',
  },
  {
    id: 'holy',
    domain: 'pl.holy.com',
    platform: 'shopify',
    schedule: '0 2 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'ucp-inventory',
    ratePerSecond: 1,
    durationSeconds: 60,
    requiresProxy: true,
    endpoint: 'https://pl.holy.com/products.json',
    enabled: true,
    currency: 'PLN',
  },
  // Prestashop - cart-reveal (mutation, proxy). Worked well in the runs.
  {
    id: 'laboratoriumpanidomu',
    domain: 'laboratoriumpanidomu.pl',
    platform: 'prestashop',
    schedule: '0 10 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'cart-probe',
    ratePerSecond: 1,
    durationSeconds: 40,
    requiresProxy: true,
    endpoint: 'https://laboratoriumpanidomu.pl/',
    enabled: true,
    currency: 'PLN',
    entityId: 'laboratoriumpanidomu',
  },
  // Shoper - basket-reveal (mutation, proxy). Verified locally, masked 0.
  {
    id: 'e-daag',
    domain: 'e-daag.com.pl',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 5,
    durationSeconds: 130,
    requiresProxy: true,
    endpoint: 'https://e-daag.com.pl/webapi/front/pl_PL/products/PLN/list',
    enabled: true,
    currency: 'PLN',
    entityId: 'e-daag',
    // The shop throttles the basket probe. The adaptive rate listens
    // to the shop and self-tunes. The rate starts at 2 per second. A
    // throttle halves it down to 0.5. Clean runs raise it by 0.25 up
    // to 3. See _internal/docs/ADAPTIVE-RATE.md.
    adaptiveRate: {
      minRequestsPerSecond: 0.5,
      maxRequestsPerSecond: 3,
      startRequestsPerSecond: 2,
      backoffFactor: 0.5,
      recoveryStep: 0.25,
      recoveryCount: 10,
    },
  },
  {
    id: 'emereedivine',
    domain: 'emereedivine.com',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 5,
    durationSeconds: 10,
    requiresProxy: true,
    endpoint: 'https://emereedivine.com/webapi/front/pl_PL/products/PLN/list',
    enabled: true,
    currency: 'PLN',
    entityId: 'emereedivine',
  },
  {
    id: 'sklepskolim',
    domain: 'sklepskolim.pl',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 5,
    durationSeconds: 70,
    requiresProxy: true,
    endpoint: 'https://sklepskolim.pl/webapi/front/pl_PL/products/PLN/list',
    enabled: true,
    currency: 'PLN',
    entityId: 'sklepskolim',
    adaptiveRate: {
      minRequestsPerSecond: 0.5,
      maxRequestsPerSecond: 3,
      startRequestsPerSecond: 2,
      backoffFactor: 0.5,
      recoveryStep: 0.25,
      recoveryCount: 10,
    },
  },
  {
    id: 'wkdzik',
    domain: 'wkdzik.pl',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 5,
    durationSeconds: 70,
    requiresProxy: true,
    endpoint: 'https://wkdzik.pl/webapi/front/pl_PL/products/PLN/list',
    enabled: true,
    currency: 'PLN',
    entityId: 'wkdzik',
    adaptiveRate: {
      minRequestsPerSecond: 0.5,
      maxRequestsPerSecond: 3,
      startRequestsPerSecond: 2,
      backoffFactor: 0.5,
      recoveryStep: 0.25,
      recoveryCount: 10,
    },
  },
  {
    id: 'brokies',
    domain: 'brokies.store',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 5,
    durationSeconds: 20,
    requiresProxy: true,
    endpoint: 'https://brokies.store/webapi/front/pl_PL/products/PLN/list',
    enabled: true,
    currency: 'PLN',
    entityId: 'brokies',
  },
  {
    id: 'risky',
    domain: 'risky.pl',
    platform: 'shoper',
    schedule: '30 4 * * *',
    window: 'both',
    mode: 'vps-mutation',
    stockSource: 'basket-reveal',
    ratePerSecond: 5,
    durationSeconds: 60,
    requiresProxy: true,
    endpoint: 'https://risky.pl/webapi/front/pl_PL/products/PLN/list',
    enabled: true,
    currency: 'PLN',
    entityId: 'risky',
  },
  ...LEGACY_PROVIDERS,
];

export const PROVIDERS: readonly ProviderConfig[] = RAW_CONFIGS.map((config) => {
  const excluded = EXCLUDED_STOCK_IDS[config.id];
  if (excluded === undefined) {
    return validateConfig(config);
  }
  return validateConfig({ ...config, excludedStockIds: excluded });
});
